-- MySQL Script generated by MySQL Workbench
-- Sat Jan 11 15:49:27 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`actividades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`actividades` (
  `id` INT NOT NULL,
  `titulo` VARCHAR(45) NULL,
  `descripcion` VARCHAR(255) NULL,
  `horario` VARCHAR(45) NULL,
  `etapaEducativa` VARCHAR(45) NULL,
  `cuota` VARCHAR(45) NULL,
  `imagenActividad` VARCHAR(255) NULL,
  `create_time` TIMESTAMP NULL,
  `update_time` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categorias` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `descripcion` INT NULL,
  `create_time` TIMESTAMP NULL,
  `update_time` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`alumnos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`alumnos` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellidos` VARCHAR(45) NULL,
  `nombreAdultoResponsable` VARCHAR(45) NULL,
  `apellidoAdultoResponsable` VARCHAR(45) NULL,
  `telefonoAdultoResponsable` VARCHAR(45) NULL,
  `emailAdultoResponsable` VARCHAR(45) NULL,
  `create_time` TIMESTAMP NULL,
  `update_time` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`actividades_categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`actividades_categorias` (
  `actividades_id` INT NOT NULL,
  `categorias_id` INT NOT NULL,
  PRIMARY KEY (`actividades_id`, `categorias_id`),
  INDEX `fk_actividades_has_categorias_categorias1_idx` (`categorias_id` ASC) VISIBLE,
  INDEX `fk_actividades_has_categorias_actividades_idx` (`actividades_id` ASC) VISIBLE,
  CONSTRAINT `fk_actividades_has_categorias_actividades`
    FOREIGN KEY (`actividades_id`)
    REFERENCES `mydb`.`actividades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_actividades_has_categorias_categorias1`
    FOREIGN KEY (`categorias_id`)
    REFERENCES `mydb`.`categorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`actividades_alumnos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`actividades_alumnos` (
  `actividades_id` INT NOT NULL,
  `alumnos_id` INT NOT NULL,
  PRIMARY KEY (`actividades_id`, `alumnos_id`),
  INDEX `fk_actividades_has_alumnos_alumnos1_idx` (`alumnos_id` ASC) VISIBLE,
  INDEX `fk_actividades_has_alumnos_actividades1_idx` (`actividades_id` ASC) VISIBLE,
  CONSTRAINT `fk_actividades_has_alumnos_actividades1`
    FOREIGN KEY (`actividades_id`)
    REFERENCES `mydb`.`actividades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_actividades_has_alumnos_alumnos1`
    FOREIGN KEY (`alumnos_id`)
    REFERENCES `mydb`.`alumnos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- Alumno
INSERT INTO alumnos VALUES(3, 'Luis', 'Gómez Sánchez', 'Marta', 'Sánchez López', '620456456', 'martasanchez@example.com', null, null);
INSERT INTO alumnos VALUES(2,'María', 'Ruiz López','Carlos ', 'Ruiz', '610984234', 'carlosruiz@gmail.com', null, null);
INSERT INTO alumnos VALUES(1,'Juan', 'Pérez García','Ana', 'López García', '600123456', 'analopez@gmail.com', null, null);

-- Categorías
INSERT INTO categorias VALUE(1,'Actividades Deportivas', 'Las actividades deportivas son aquellas prácticas físicas que buscan mejorar la condición física, mental y emocional de los participantes a través de ejercicios, juegos y competencias que involucran esfuerzo físico y habilidades específicas. ', null, null, 1);
INSERT INTO categorias VALUE(2,'Actividades Culturales', 'A través de las actividades culturales, los individuos tienen la oportunidad de conocer, compartir y reflexionar. Estas actividades no solo enriquecen la experiencia personal de los participantes, promoviendo la diversidad y el entendimiento mutuo.', null, null, 1);
INSERT INTO categorias VALUE(3,'Idiomas', ' Estas actividades pueden incluir clases formales, intercambios lingüísticos, talleres, juegos, sesiones de conversación, ejercicios de comprensión auditiva, lecturas, y mucho más.', null, null, 1);

-- Actividades
INSERT INTO actividades VALUES(9, 'Actividad en el Museo', 'Disfruta de la increible actividad en el museo para tus hijos. Verán los mejores cuadros en el museo del Prado', 
'Lunes a las 10:00 horas','1º Bachiller' ,149.99, 'actividadImagen.jpg', null, null,1);
INSERT INTO actividades VALUES(8, 'Actividad de Inglés', 'Disfruta de la increible actividad de inglés para tus hijos. Permite que aprendan múltiples idiomas y que se desarrollen en el extranjero.', 
'Lunes a las 9:00 horas','1º Bachiller' ,2.99, 'actividadImagen.jpg', null, null,1);
INSERT INTO actividades VALUES(7, 'Actividad de Balón Quemado', 'Disfruta de la increible actividad de balón quemado para tus hijos. Únete a nosotros para un día lleno de acción y deporte.', 
'Lunes a las 11:00 horas','2º Bachiller' ,9.99, 'actividadImagen.jpg', null, null,1);
INSERT INTO actividades VALUES(6, 'Actividad de Pelota Mano', 'Disfruta de la increible actividad de pelota mano para tus hijos. Únete a nosotros para un día lleno de acción y deporte.', 
'Lunes a las 12:00 horas','4º Primaria' ,23.99, 'actividadImagen.jpg', null, null,1);
INSERT INTO actividades VALUES(5, 'Actividad de Natación', 'Disfruta de la increible actividad de natación para tus hijos. Únete a nosotros para un día lleno de acción y deporte.', 
'Lunes a las 19:00 horas','6º Primaria' ,99.99, 'actividadImagen.jpg', null, null,1);
INSERT INTO actividades VALUES(4, 'Actividad de Volley', 'Disfruta de la increible actividad de volley para tus hijos. Únete a nosotros para un día lleno de acción y deporte.', 
'Lunes a las 16:00 horas','3º Primaria' ,10.99, 'actividadImagen.jpg', null, null,1);
INSERT INTO actividades VALUES(3, 'Actividad de Fútbol', 'Disfruta de la increible actividad de fútbol para tus hijos. Únete a nosotros para un día lleno de acción y deporte.', 
'Lunes a las 16:00 horas','3º Primaria' ,50.00, 'actividadImagen.jpg', null, null,1);
INSERT INTO actividades VALUES(2, 'Actividad de Tenis', 'Disfruta de la increible actividad de tenis para tus hijos. Únete a nosotros para un día lleno de acción y deporte.', 
'Lunes a las 18:00 horas','4º ESO' ,50.00, 'actividadImagen.jpg', null, null,1);
INSERT INTO actividades VALUES(1, 'Actividad de Baloncesto', 'Disfruta de la increible actividad de baloncesto para tus hijos. Únete a nosotros para un día lleno de acción y deporte.', 
'Lunes a las 14:00 horas','3º ESO' ,25.00, 'actividadImagen.jpg', null, null,1);

-- Actividad - Alumno
INSERT INTO actividades_alumnos VALUES(1,1, 'Lunes día 6 de diciembre', 'Pendiente', null, null);
INSERT INTO actividades_alumnos VALUES(2,2, 'Sábado día 4 de diciembre', 'Pendiente', null, null);
INSERT INTO actividades_alumnos VALUES(3,3, 'Jueves día 2 de diciembre', 'Pendiente', null, null);

-- Actividad - Categoría
INSERT INTO actividades_categorias VALUES(1,1, null, null);
INSERT INTO actividades_categorias VALUES(2,1, null, null);
INSERT INTO actividades_categorias VALUES(3,1, null, null);
INSERT INTO actividades_categorias VALUES(4,1, null, null);
INSERT INTO actividades_categorias VALUES(5,1, null, null);
INSERT INTO actividades_categorias VALUES(6,1, null, null);
INSERT INTO actividades_categorias VALUES(7,1, null, null);
INSERT INTO actividades_categorias VALUES(8,3, null, null);
INSERT INTO actividades_categorias VALUES(9,2, null, null);



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
